export const AddTableDeviceColumns = [
  {
    id: "12",
    title: "Device",
    key: "device",
    visible: true,
    category: "Attributes",
  },
  {
    id: "1",
    title: "Average CPC",
    key: "average_cpc",
    visible: true,
    category: "Performance",
  },
  {
    id: "2",
    title: "Clicks",
    key: "clicks",
    visible: true,
    category: "Performance",
  },
  {
    id: "3",
    title: "Conversions",
    key: "conversions",
    visible: true,
    category: "Conversions",
  },
  {
    id: "4",
    title: "Cost",
    key: "cost",
    visible: true,
    category: "Performance",
  },
  {
    id: "5",
    title: "Cost Per Conversion",
    key: "cost_per_conversion",
    visible: true,
    category: "Conversions",
  },
  {
    id: "6",
    title: "CTR",
    key: "ctr",
    visible: true,
    category: "Performance",
  },
  {
    id: "7",
    title: "Impressions",
    key: "impressions",
    visible: true,
    category: "Performance",
  },
  {
    id: "8",
    title: "Interaction Rate",
    key: "interaction_rate",
    visible: true,
    category: "Performance",
  },
  {
    id: "9",
    title: "Interactions",
    key: "interactions",
    visible: true,
    category: "Performance",
  },
  {
    id: "11",
    title: "Conversion Rate",
    key: "conversion_rate",
    visible: true,
    category: "Conversions",
  },
];

export const AddTableAgeColumns = [
  {
    id: "15",
    title: "Age Range",
    key: "age_range",
    visible: true,
    category: "Attributes",
  },
  {
    id: "1",
    title: "Average CPC",
    key: "average_cpc",
    visible: true,
    category: "Performance",
  },
  {
    id: "2",
    title: "Clicks",
    key: "clicks",
    visible: true,
    category: "Performance",
  },
  {
    id: "3",
    title: "Conversions",
    key: "conversions",
    visible: true,
    category: "Conversions",
  },
  {
    id: "4",
    title: "Cost",
    key: "cost",
    visible: true,
    category: "Performance",
  },
  {
    id: "5",
    title: "Cost Per Conversion",
    key: "cost_per_conversion",
    visible: true,
    category: "Conversions",
  },
  {
    id: "6",
    title: "CTR",
    key: "ctr",
    visible: true,
    category: "Performance",
  },
  {
    id: "7",
    title: "Impressions",
    key: "impressions",
    visible: true,
    category: "Performance",
  },
  {
    id: "8",
    title: "Interaction Rate",
    key: "interaction_rate",
    visible: true,
    category: "Performance",
  },
  {
    id: "9",
    title: "Interactions",
    key: "interactions",
    visible: true,
    category: "Performance",
  },
  {
    id: "11",
    title: "Conversion Rate",
    key: "conversion_rate",
    visible: true,
    category: "Conversions",
  },
];

export const AddTableGenderColumns = [
  {
    id: "14",
    title: "Gender",
    key: "gender",
    visible: true,
    category: "Attributes",
  },
  {
    id: "1",
    title: "Average CPC",
    key: "average_cpc",
    visible: true,
    category: "Performance",
  },
  {
    id: "2",
    title: "Clicks",
    key: "clicks",
    visible: true,
    category: "Performance",
  },
  {
    id: "3",
    title: "Conversions",
    key: "conversions",
    visible: true,
    category: "Conversions",
  },
  {
    id: "4",
    title: "Cost",
    key: "cost",
    visible: true,
    category: "Performance",
  },
  {
    id: "5",
    title: "Cost Per Conversion",
    key: "cost_per_conversion",
    visible: true,
    category: "Conversions",
  },
  {
    id: "6",
    title: "CTR",
    key: "ctr",
    visible: true,
    category: "Performance",
  },
  {
    id: "7",
    title: "Impressions",
    key: "impressions",
    visible: true,
    category: "Performance",
  },
  {
    id: "8",
    title: "Interaction Rate",
    key: "interaction_rate",
    visible: true,
    category: "Performance",
  },
  {
    id: "9",
    title: "Interactions",
    key: "interactions",
    visible: true,
    category: "Performance",
  },
  {
    id: "11",
    title: "Conversion Rate",
    key: "conversion_rate",
    visible: true,
    category: "Conversions",
  },
];
export const AddbidStrategyColumns = [
  {
    id: "1",
    key: "bid_strategy_type",
    title: "Bid Strategy Type",
    visible: true,
    category: "Performance",
  },
  {
    id: "2",
    key: "campaign_name",
    title: "Campaign Name",
    visible: false,
    category: "Performance",
  },
  {
    id: "3",
    key: "clicks",
    title: "Clicks",
    visible: true,
    category: "Performance",
  },
  {
    id: "4",
    key: "impressions",
    title: "Impressions",
    visible: true,
    category: "Performance",
  },
  {
    id: "5",
    key: "ctr",
    title: "CTR (%)",
    visible: true,
    category: "Performance",
  },
  {
    id: "6",
    key: "conversions",
    title: "Conversions",
    visible: true,
    category: "Conversions",
  },
  {
    id: "7",
    key: "conversions_rate", // correct key name from API
    title: "Conversion Rate (%)",
    visible: true,
    category: "Conversions",
  },
  {
    id: "8",
    key: "cost",
    title: "Cost",
    visible: true,
    category: "Performance",
  },
  {
    id: "9",
    key: "average_cpc",
    title: "Avg CPC",
    visible: true,
    category: "Performance",
  },
  {
    id: "10",
    key: "cost_per_conversion",
    title: "Cost/Conversion",
    visible: false,
    category: "Conversions",
  },
  {
    id: "11",
    key: "interaction_rate",
    title: "Interaction Rate",
    visible: false,
    category: "Performance",
  },
  {
    id: "12",
    key: "interactions",
    title: "Interactions",
    visible: false,
    category: "Performance",
  },
];

